# Generated by Django 4.2.7 on 2025-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_random_todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomtask',
            name='description',
        ),
    ]
