# Generated by Django 4.2.7 on 2025-03-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'هشتگ',
                'verbose_name_plural': 'هشتگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('priority', models.CharField(choices=[('مهمه برام', 'مهمه برام'), ('حسش بود انجام میدم', 'حسش بود انجام میدم'), ('حسش فعلا نیس', 'حسش فعلا نیس')], default='حسش فعلا نیس', max_length=50, verbose_name='اولویت')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('hashtags', models.ManyToManyField(blank=True, related_name='tasks', to='To_Do_List.hashtag', verbose_name='هشتگ\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تسک',
                'verbose_name_plural': 'تسک\u200cها',
                'ordering': ['-date_created'],
            },
        ),
    ]
