# Generated by Django 4.2.7 on 2025-05-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cold', 'cold'), ('hot', 'hot'), ('rainy', 'rainy'), ('snowy', 'snowy'), ('sunny', 'sunny')], max_length=100)),
            ],
        ),
    ]
