# Generated by Django 4.2.7 on 2025-05-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathertext',
            options={'verbose_name': 'متن برای آب و هوا', 'verbose_name_plural': 'متن برای آب و هواs'},
        ),
    ]
