# Generated by Django 4.2.7 on 2025-05-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_text', '0002_alter_weathertext_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertext',
            name='category',
            field=models.CharField(choices=[('cold', 'cold'), ('hot', 'hot'), ('rainy', 'rainy'), ('snowy', 'snowy'), ('sunny', 'sunny')], max_length=100, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='weathertext',
            name='text',
            field=models.CharField(max_length=100, verbose_name='متن'),
        ),
    ]
